[package]
name = "scorefall-font"
version = "0.1.0"
authors = ["Jeron Aldaron Lau <jeronlau@plopgrizzly.com>"]
edition = "2018"

[dependencies]
# score2svg = {path = "../score2svg"}
svgdom = "0.18"
serde_json = "1.0"
muon-rs = "0.2"
serde = "1.0"
serde_derive = "1.0"
